export const APP_ID = 'lean_diet_v101_perfect_pyramid';

export const COLORS = {
  p: '#F59E0B', 
  c: '#3B82F6', 
  f: '#BE123C', 
  success: '#10B981', 
  warning: '#FBBF24',
  danger: '#EF4444',
  bg: '#FFFDFB'
};

export const FOOD_DB: Record<string, { p: number, c: number, f: number, emoji: string }> = {
  '鸡胸肉': { p: 31, c: 0, f: 2.5, emoji: '🍗' },
  '瘦牛肉': { p: 26, c: 0, f: 4, emoji: '🥩' },
  '猪里脊': { p: 20, c: 0, f: 7, emoji: '🥓' },
  '瘦羊肉': { p: 18, c: 0, f: 12, emoji: '🍖' },
  '鸭胸肉': { p: 16, c: 0, f: 15, emoji: '🦆' },
  '咖喱鸡翅(去皮)': { p: 24, c: 1, f: 5, emoji: '🍗' },
  '咖喱牛肉': { p: 28, c: 2, f: 6, emoji: '🥩' },
  '排骨': { p: 18, c: 0, f: 20, emoji: '🍖' },
  '瘦肉丸': { p: 18, c: 12, f: 8, emoji: '🍡' },
  '兔肉': { p: 21, c: 0, f: 2, emoji: '🐇' },
  '虾仁': { p: 23, c: 0, f: 1, emoji: '🍤' },
  '鳕鱼': { p: 20, c: 0, f: 1, emoji: '🐟' },
  '三文鱼': { p: 20, c: 0, f: 13, emoji: '🍣' },
  '鲈鱼': { p: 18, c: 0, f: 3, emoji: '🐟' },
  '巴沙鱼': { p: 16, c: 0, f: 1.5, emoji: '🐟' },
  '鲫鱼': { p: 17, c: 0, f: 4, emoji: '🐟' },
  '金枪鱼': { p: 24, c: 0, f: 1, emoji: '🐟' },
  '扇贝': { p: 15, c: 3, f: 1, emoji: '🐚' },
  '花蛤肉': { p: 12, c: 3, f: 1, emoji: '🐚' },
  '螃蟹': { p: 14, c: 1, f: 2, emoji: '🦀' },
  '鱿鱼': { p: 15, c: 1, f: 1, emoji: '🦑' },
  '海参': { p: 16, c: 0.4, f: 0.2, emoji: '🥒' },
  '鸡蛋': { p: 13, c: 1, f: 10, emoji: '🥚' },
  '蛋白': { p: 4, c: 0, f: 0, emoji: '⚪' },
  '希腊酸奶': { p: 10, c: 4, f: 0, emoji: '🍦' },
  '脱脂牛奶': { p: 3.4, c: 5, f: 0.1, emoji: '🥛' },
  '全脂牛奶': { p: 3.3, c: 4.8, f: 3.6, emoji: '🥛' },
  '北豆腐': { p: 12, c: 3, f: 5, emoji: '🧊' },
  '内脂豆腐': { p: 5, c: 2, f: 1, emoji: '🍮' },
  '豆浆': { p: 3, c: 1.2, f: 1.6, emoji: '🥤' },
  '豆干': { p: 16, c: 4, f: 12, emoji: '🍢' },
  '腐竹': { p: 44, c: 18, f: 21, emoji: '🥢' },
  '纳豆': { p: 18, c: 14, f: 10, emoji: '🥣' },
  '全麦面包': { p: 10, c: 45, f: 3, emoji: '🍞' },
  '欧包': { p: 9, c: 52, f: 1.5, emoji: '🥖' },
  '自制德包': { p: 11, c: 48, f: 2, emoji: '🍞' },
  '燕麦': { p: 12, c: 66, f: 7, emoji: '🥣' },
  '糙米': { p: 7.5, c: 75, f: 2.5, emoji: '🍚' },
  '小米': { p: 9, c: 72, f: 3, emoji: '🥣' },
  '紫薯': { p: 1.6, c: 25, f: 0.2, emoji: '🍠' },
  '红薯': { p: 1.1, c: 24, f: 0.2, emoji: '🍠' },
  '玉米': { p: 4, c: 19, f: 1.2, emoji: '🌽' },
  '荞麦面': { p: 10, c: 68, f: 2, emoji: '🍜' },
  '意面': { p: 14, c: 64, f: 6, emoji: '🍝' },
  '西兰花': { p: 3, c: 7, f: 0.6, emoji: '🥦' },
  '菠菜': { p: 2.6, c: 3, f: 0.3, emoji: '🥬' },
  '小白菜': { p: 1.5, c: 2, f: 0.1, emoji: '🥬' },
  '生菜': { p: 1.2, c: 2, f: 0.1, emoji: '🥬' },
  '白萝卜': { p: 0.9, c: 4, f: 0.1, emoji: '🥕' },
  '冬瓜': { p: 0.4, c: 2, f: 0.1, emoji: '🥒' },
  '番茄': { p: 0.9, c: 4, f: 0.2, emoji: '🍅' },
  '南瓜': { p: 0.7, c: 5, f: 0.1, emoji: '🎃' },
  '香菇': { p: 3, c: 5, f: 0.3, emoji: '🍄' },
  '木耳': { p: 1.5, c: 6, f: 0.2, emoji: '🍄' },
  '莲藕': { p: 1, c: 3, f: 0.1, emoji: '🥗' },
  '芹菜': { p: 0.8, c: 2, f: 0.1, emoji: '🌿' },
  '牛油果': { p: 2, c: 8, f: 15, emoji: '🥑' },
  '坚果': { p: 15, c: 20, f: 55, emoji: '🥜' },
};

export const MASTER_RECIPE_DB = [
  { id: 1, type: 'morning', name: '杂豆燕麦粥', emoji: '🥤', p: 12, f: 5, c: 10, ingredients: [{name: '杂豆', amt: '50g'}], steps: '1. 杂豆泡发。2. 加水打泥煮熟。' },
  { id: 2, type: 'morning', name: '牛油果鸡蛋三明治', emoji: '🥪', p: 18, f: 14, c: 32, ingredients: [{name: '欧包', amt: '1片'}, {name: '鸡蛋', amt: '1个'}, {name: '牛油果', amt: '0.5个'}], steps: '1. 面包烤脆。2. 铺牛油果泥及白煮蛋片。' },
  { id: 3, type: 'morning', name: '欧包/自制德包', emoji: '🥖', p: 11, f: 2, c: 48, ingredients: [{name: '欧包', amt: '100g'}], steps: '1. 复烤切片。' },
  { id: 4, type: 'morning', name: '水煮蛋', emoji: '🥚', p: 13, f: 10, c: 1, ingredients: [{name: '鸡蛋', amt: '2个'}], steps: '1. 沸水煮 8分钟。' },
  { id: 5, type: 'morning', name: '蒸玉米红薯', emoji: '🍠', p: 6, f: 2, c: 55, ingredients: [{name: '玉米', amt: '1根'}, {name: '红薯', amt: '150g'}], steps: '1. 洗净同蒸 25分钟。' },
  { id: 6, type: 'morning', name: '清淡绿豆稀', emoji: '🥣', p: 8, f: 1, c: 45, ingredients: [{name: '绿豆', amt: '30g'}, {name: '大米', amt: '20g'}], steps: '1. 煮至开花起沙。' },
  { id: 7, type: 'morning', name: '全麦肉包', emoji: '🥩', p: 12, f: 10, c: 40, ingredients: [{name: '肉包', amt: '2个'}], steps: '1. 早餐上锅蒸 15分钟。' },
  { id: 11, type: 'noon', name: '清蒸鲈鱼', emoji: '🐟', p: 38, f: 6, c: 2, ingredients: [{name: '鲈鱼', amt: '250g'}], steps: '1. 鲈鱼抹盐姜片旺火蒸 8分钟淋酱油。' },
  { id: 12, type: 'noon', name: '芹菜炒虾仁', emoji: '🍤', p: 26, f: 2, c: 5, ingredients: [{name: '虾仁', amt: '120g'}, {name: '芹菜', amt: '200g'}], steps: '1. 虾仁焯熟下芹菜大火快炒。' },
  { id: 13, type: 'noon', name: '咖喱牛肉/咖喱鸡翅', emoji: '🥩', p: 42, f: 12, c: 3, ingredients: [{name: '牛肉/鸡翅', amt: '200g'}], steps: '1. 提前咖喱好餐用，高蛋白王牌。' },
  { id: 14, type: 'noon', name: '烤巴沙鱼排', emoji: '🐟', p: 28, f: 3, c: 1, ingredients: [{name: '巴沙鱼', amt: '200g'}], steps: '1. 撒盐和黑椒，180度烤 12分钟。' },
  { id: 15, type: 'noon', name: '烤鸡胸肉', emoji: '🍗', p: 48, f: 5, c: 4, ingredients: [{name: '鸡胸肉', amt: '200g'}], steps: '1. 鸡胸腌制，空炸 180度烤 15分钟。' },
  { id: 16, type: 'noon', name: '青椒炒鸡蛋', emoji: '🍳', p: 15, f: 12, c: 5, ingredients: [{name: '鸡蛋', amt: '3个'}, {name: '青椒', amt: '100g'}], steps: '1. 鸡蛋炒散混入青椒。' },
  { id: 17, type: 'noon', name: '滑蛋瘦牛肉', emoji: '🥩', p: 35, f: 10, c: 3, ingredients: [{name: '瘦牛肉', amt: '120g'}, {name: '鸡蛋', amt: '2个'}], steps: '1. 牛肉滑熟拌蛋液快炒。' },
  { id: 18, type: 'noon', name: '豆干菠菜汤', emoji: '🥣', p: 12, f: 4, c: 6, ingredients: [{name: '豆干', amt: '1块'}, {name: '菠菜', amt: '100g'}], steps: '1. 豆干煮沸下菜调味。' },
  { id: 31, type: 'night', name: '手撕鸡', emoji: '🥗', p: 42, f: 8, c: 3, ingredients: [{name: '鸡腿肉', amt: '200g'}], steps: '1. 煮熟撕条加生抽醋凉拌。' },
  { id: 32, type: 'night', name: '虾仁滑蛋', emoji: '🍤', p: 30, f: 10, c: 4, ingredients: [{name: '虾仁', amt: '100g'}, {name: '鸡蛋', amt: '2个'}], steps: '1. 虾仁滑熟拌蛋液滑炒。' },
  { id: 33, type: 'night', name: '韭菜炒鸡蛋', emoji: '🍳', p: 14, f: 11, c: 6, ingredients: [{name: '鸡蛋', amt: '2个'}, {name: '韭菜', amt: '150g'}], steps: '1. 韭菜炒软放入蛋划散。' },
  { id: 34, type: 'night', name: '炒花蛤', emoji: '🐚', p: 12, f: 2, c: 5, ingredients: [{name: '花蛤', amt: '300g'}], steps: '1. 爆姜丝炒至开口即可。' },
  { id: 35, type: 'night', name: '凉拌木耳腐竹', emoji: '🥢', p: 18, f: 8, c: 10, ingredients: [{name: '腐竹', amt: '50g'}, {name: '木耳', amt: '30g'}], steps: '1. 焯水后调味汁凉拌。' },
  { id: 36, type: 'night', name: '酸菜牛肉', emoji: '🥩', p: 32, f: 12, c: 8, ingredients: [{name: '牛肉', amt: '120g'}, {name: '酸菜', amt: '100g'}], steps: '1. 牛肉滑熟混入酸菜炒匀。' },
  { id: 37, type: 'night', name: '哈佛蔬菜汤', emoji: '🥣', p: 6, f: 0.5, c: 15, ingredients: [{name: '洋葱/番茄/南瓜', amt: '各 100g'}], steps: '1. 纯素慢煮补营养。' },
  { id: 38, type: 'night', name: '牛肉丸冬瓜汤', emoji: '🥩', p: 28, f: 12, c: 8, ingredients: [{name: '肉丸', amt: '6颗'}, {name: '冬瓜', amt: '200g'}], steps: '1. 冬瓜煮透下丸子。' },
  { id: 39, type: 'night', name: '蒸排骨', emoji: '🍖', p: 22, f: 18, c: 5, ingredients: [{name: '小排', amt: '150g'}], steps: '1. 蒜末豆豉蒸 20分钟。' },
  { id: 40, type: 'night', name: '白灼虾仁', emoji: '🍤', p: 24, f: 1, c: 2, ingredients: [{name: '大虾仁', amt: '120g'}], steps: '1. 沸水姜片烫熟。' },
];
